# Generated by Django 3.0.5 on 2020-05-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
    ]
